### ISSUE TITLE
Curated list of SS4 compatible modules

### ISSUE THREAD

**Issue by phptek** [silverstripe/cwp-recipe-basic#1]
A lot of work has gone on upgrading CWP-* modules, as well as individual modules to be SS4 compatible; Does anyone have a timeline as to how long it'll be before a beta version of recipe-basic is available?

If so, and no-one knows of anything other than upgraded modules as expected changes, then I'll compile one myself.

**Comment by robbieaverill** [comment]
Hey @phptek - we're assembling the recipes as we speak. You can follow a relatively fully curated list at https://github.com/silverstripe/cwp-installer/pull/5
