### ISSUE TITLE
Includes fulltextsearch without also including cwp-recipe-search

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp-recipe-basic#2]
See https://github.com/silverstripe/cwp-recipe-basic/blob/master/composer.json. So you get the module without the support code required for CWP. 

The installer includes `cwp/cwp-recipe-search`, which sets up the module properly: https://github.com/silverstripe/cwp-installer/blob/master/composer.json

Aside: Where is `cwp-recipe-basic` included anyway? I can't see it in `cwp-recipe-core` or the installer.

**Comment by robbieaverill** [comment]
So `cwp-recipe-basic` is a CWP 1.x only recipe. In CWP 2.x we're using the search recipe which includes the required search modules and code, but you don't have to install it

**Comment by robbieaverill** [comment]
I think this is a misunderstanding, but feel free to reopen if not

**Comment by chillu** [comment]
Ah right, sorry for not responding!
