### ISSUE TITLE
File_ShowInSearch doesn't exist

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp-recipe-basic#3]
Composer.json:
```json
"cwp/cwp-recipe-basic": "~1.8.1@stable",
"cwp-themes/default": "~1.3.0@stable",
"cwp/agency-extensions": "^1.1"
```

Using default CWP search classes

When I do a search I get the following solr error

```
ERROR org.apache.solr.core.SolrCore  – org.apache.solr.common.SolrException: undefined field File_ShowInSearch
```

If I comment out `$query->exclude('File_ShowInSearch', 0);` in `CwpSearchEngine.php:45` the error resolves (not that this would be a good idea)

**Comment by dhensby** [comment]
I believe this was fixed by https://github.com/silverstripe/cwp/pull/64
